### ISSUE TITLE
output file is created when no input provided

### ISSUE THREAD

**Issue by mrjoel** [jszakmeister/rst2ctags#8]
In a case where no input files are provided, the output file shouldn't be opened/created. It's admittedly a minor issue, but I ran into it when I was doing an initial test installation and it resulted in several "tags" files littered throughout my git repo.

In a quick look, it looks like the output is opened before the iteration on args. It may match expectations better to at least check if args remain, or perhaps better yet deferring opening (and implicitly creating) the output file until content is available to write. This latter approach would also cover cases of not creating an output file when an invalid file is provided as input.

**Comment by jszakmeister** [comment]
> In a case where no input files are provided, the output file shouldn't be opened/created. It's admittedly a minor issue, but I ran into it when I was doing an initial test installation and it resulted in several "tags" files littered throughout my git repo.

Yep, a quick check of args could prevent leaving an empty tags file, though ctags will generate an empty tags file in this case... so it might be worthwhile to preserve the behavior.

> or perhaps better yet deferring opening (and implicitly creating) the output file until content is available to write. This latter approach would also cover cases of not creating an output file when an invalid file is provided as input.

I'm always in a quandary about the lazy open approach since it's also possible that you don't have permission to open the tags file and you've potentially done significant work before discovering that fact.  I think I'll follow what ctags does here, which create the tags, writes the header, and then starts loading in the content.

Thanks for the bug report... I found two other things that I hadn't noticed:

1. I'm not sorting all the tags, only the tags per file.
2. The header will be written out per file.

While my main use-case is for use with TagBar, I do want to fix those issues as well.  Thanks for the heads up.  Hopefully, I can get fix up the issues this week, but if not, it'll be taken care of by next week.

**Comment by jszakmeister** [comment]
> Yep, a quick check of args could prevent leaving an empty tags file, though ctags will generate an empty tags file in this case... so it might be worthwhile to preserve the behavior.

I had this wrong.  It'll create an empty tags file when a non-existent path is provided.  If no files are provided, it doesn't do anything, so I'll implement that behavior.

**Comment by mrjoel** [comment]
Sounds workable - thanks for the quick fix!
